### ISSUE TITLE
Player cant create Clans

### ISSUE THREAD

**Issue by Alphazockt135** [Wertzui123/BedrockClans#10]
**Everytime** a _player_ try use /clan **create**
It say cannot use this **subcommand** what can i do i need this Plugin so much ### pls help

**Comment by HimmelKreis4865** [comment]
Hello @Alphazockt135,

Please add the permission `bedrockclans.cmd.create` to every group who should create clans.

**Comment by Alphazockt135** [comment]
Thanks so muc
