### ISSUE TITLE
Crashes everytims

### ISSUE THREAD

**Issue by Alphazockt135** [Wertzui123/BedrockClans#11]
Everytime someone want to create a clan he gets Internal server error

**Comment by HimmelKreis4865** [comment]
Hello @Alphazockt135,
Please send your console error here (not internal server error), the red message in console, so Wertzui123 can fix this error.

**Comment by Alphazockt135** [comment]
[11:53:46] [Server thread/CRITICAL]: ErrorException: "Undefined index: clan_create_cost" (EXCEPTION) in "plugins/BedrockClans_dev-30.phar/src/Wertzui123/BedrockClans/Main" at line 255

**Comment by Alphazockt135** [comment]
I tryed use an older version but it still crashes

**Comment by HimmelKreis4865** [comment]
yea, please tell me if there's a file `settings.yml` and `messages.yml` in `/plugin_data/BedrockClans`

**Comment by HimmelKreis4865** [comment]
and if it has the key `clan_create_cost` in it.

**Comment by Alphazockt135** [comment]
Yes it is but i dont have settings i have only config

**Comment by HimmelKreis4865** [comment]
So please create the file `messages.yml` manually. Copy and paste the content of the <a href="https://github.com/Wertzui123/BedrockClans/blob/master/resources/messages.yml"> messages file </a> to your local file.

**Comment by Alphazockt135** [comment]
Geht trotzdem nicht

**Comment by Alphazockt135** [comment]
I mean it doesn't work

**Comment by HimmelKreis4865** [comment]
so you created the file correctly, saved the content in it, and restarted?

**Comment by HimmelKreis4865** [comment]
I don't think the content is there correctly. Otherwise, Wertzui123 has to fix it.

**Comment by Wertzui123** [comment]
Hi. Try to copy and paste the <a href="https://github.com/Wertzui123/BedrockClans/blob/master/resources/config.yml">contents of the config.yml</a> into your plugin_data/BedrockClans/config.yml and try creating a clan again.

**Comment by Alphazockt135** [comment]
Thanks it works i think the config was broken
