### ISSUE TITLE
Restrictions on clan names

### ISSUE THREAD

**Issue by MonoAdrian23** [Wertzui123/BedrockClans#16]
Hey Wertzui!

Erstmal muss ich ganz ehrlich sagen!
Danke für das beste Clan Plugin was aktuell am Start ist!
Aber einen kleinen Vorschlag hab ich dennoch.
Ein Limit an Zeichen die man für einen Clannamen nutzen kann.
Es ist etwas blöd wenn jmd einen Clannamen macht wie zb xxxxxxxxxxxxxxxxxxxxxxxxxxxx
Ein Limit in der Config.yml einstellbar würde das Plugin perfekt machen!

Ich bedanke mich ganz herzlich bei dir und wünsche dir einen Schönen Tag!

**Comment by Wertzui123** [comment]
Finally implemented after 3 years 😄
