### ISSUE TITLE
Komischer Clan Bug 

### ISSUE THREAD

**Issue by DragonfireHD** [Wertzui123/BedrockClans#21]
Hallo Wertzui lange nicht mehr von dir gehört 🙂

Also warum ich dich anschreibe ist folgendes ich habe dein Clan Plugin auf dem Server es funktioniert super dennoch hab ich ein kleinen bug wegen dem clan namen und generell der Clan an sich löscht sich bei jeden rejoin und der name wird ebenfalls gelöscht 

Hast du ein tipp woran der fehler liegen kann?

**Comment by DragonfireHD** [comment]
Gemeldet wurde der Bug von mehreren Spieler

**Comment by Wertzui123** [comment]
Schick mir mal deine `config.yml`.

**Comment by DragonfireHD** [comment]
---
# BedrockClans - Copyright 2019 - 2020 Wertzui123
# Don't edit this if you don't know what you're doing
config-version: 3.2
# Banned clan names
banned_clan_names: 
 - Hacker
 - Owner
 - Admin
 - Support Team
 - Supporter
 - Moderator
 - Co-Owner
 - 88
 - Hitler
 - Adolf
 - Builder
 - Nazi
 - Team
 - Staff
 - Server
 - Clan
# Commands
command:
 clan:
  command: clan
  description: Erstellen, Clans löschen und verwalten
  usage: "/clan <subcommand: string>"
  aliases: ['clan']
# Should  /clan create cost money? (EconomyAPI)
create_costs: true
# How much money it should cost to create a clan when create_costs is enabled
clan_create_costs: 500
# Whether /clan chat should be enabled or disabled
chat:
 enabled: true
 on: "on" # /clan chat on
 off: "off" # /clan chat off
# Whether /clan home should be enabled or disabled
home:
 enabled: true
# How many seconds an invitation is valid
invitation_expire_time: 3000
# The display-names and colors for the clan ranks
ranks:
 member:
  name: "Clan-Mitglied"
  color: "§2"
 vim:
  name: "Clan-Ältester"
  color: "§3"
 coleader:
  name: "Vize-Anführer"
  color: "§6"
 leader:
  name: "Clan-Anführer"
  color: "§e"
bank:
 enabled: true
 withdraw:
  # All members (except the clan leader) have to wait this long (in hours) between withdrawing from the clan's bank
  cooldown: 24
  maximum:
   # How much percent of the money on the clan bank can be withdrawn from members with the following ranks
   member: 500
   vim: 1500
   coleader: 4500
   leader: 10000

**Comment by Wertzui123** [comment]
Nächstes mal am besten so:

```yaml
Deine config.yml
```

Ich sehe sonst keinen Fehler. Kommt eine Nachricht in der Konsole?

**Comment by DragonfireHD** [comment]
Nein Konsole wird nichts angezeigt

**Comment by DragonfireHD** [comment]
Also die clans sind alle Kategoriert die sind aufgelistet aber die Clans die die Spieler erstellt haben wenn sie rejoine werden sie quasi rausgeworfen und sie müssen wieder einen neuen gründen

**Comment by Wertzui123** [comment]
Was meinst du mit "die Clans sind kategorisiert"?

**Comment by DragonfireHD** [comment]
Ja die werden ja in ein zwischen datei gespeichert in den clan Ordner

**Comment by DragonfireHD** [comment]
Gibt es vielleicht irgendwelche plugins die sowas löschen können oder liegt dies am Clan Plugin

**Comment by Wertzui123** [comment]
Wieso hast du die Issue geschlossen?
