### ISSUE TITLE
Bug: Clan wird gecleart sobald man denn Server restartet

### ISSUE THREAD

**Issue by DragonfireHD** [Wertzui123/BedrockClans#22]
Bug: Spieler Createn für 500 Dollar Clans dennoch werden sie bei jeden Server Restart gecleart und ich habe in den Code etwas reingeschaut dennoch  konnte ich denn fehler nicht erkennen oder komplett fixen deswegen komme ich erneut zu dir um zu fragen ob du es fixen könntest

Also getstet habe ich es 2 mal mit ein  Spieler und Teamler

Beide verlieren nach ein Server Restart ihr Clan und müssen jedes mal ein neuen erstellen das ist für die selbstverständlich ärgerlich

**Comment by Wertzui123** [comment]
Bei deinen Problem scheint eher deine Config falsch eingestellt oder deine Datenbank kapput zu sein. Probiere bitte ob BedrockClans auf einem neuen Server ähnliche Fehler erzeugt.

**Comment by DragonfireHD** [comment]
Welche datenbank es gibt kein MySQL ich hab an der Config nichts geändert es ist deine Original Version

**Comment by DragonfireHD** [comment]
Und wenn es ein config fehler wäre dann müsste der Server abstürzen das ist der häufige fahl oder es gäbe ein Crashdump

**Comment by DragonfireHD** [comment]
Es liegt am Server Restart sobald man dies tut wird der Owner seines Clans nicht angezeigt und einfach zurückgesetzt und muss denn Clan erneut gründen schau an sie bitte nach fehler im code ich möchte nicht unhöflich klingen aber ich kann so oder so nicht richtig programmieren also kann ich selbst am Code nicht viel verändert haben

**Comment by efor89** [comment]
nutzt du auch die neuste version?

**Comment by efor89** [comment]
ich hatte das selbe problem in einer älteren versin deswegen die frage

**Comment by efor89** [comment]
https://poggit.pmmp.io/ci/Wertzui123/BedrockClans

**Comment by DragonfireHD** [comment]
Ja genau die neuste

**Comment by DragonfireHD** [comment]
@efor89 ab welche Version tritt dies auf weißt du das vielleicht

**Comment by DragonfireHD** [comment]
@efor89 ich finde es doof immer die issue immer gleich zu blockieren oder zu closen anstatt die Bugs zu lösen? 

Ich bin ja jetzt nicht der einzige der das Problem hat 
Also dann muss es am code liegen wir wollen dich nicht ärgern @Wertzui123 aber wir wollen das beste aus dem Plugin machen und wollen dir jegliche bugs und fehler sagen damit du wenigstens fixen kannst damit wir doch aich in ruhe lassen. 🙂

**Comment by efor89** [comment]
kann ich dir nicht sagen mit welcher version ich das problem hatte is aber schon paar wochen her

**Comment by DragonfireHD** [comment]
@efor89 ah ok

**Comment by Wertzui123** [comment]
Deine Datenbank sind die "clans.json" und "players.json" Dateien. Außerdem vermute ich, dass du mit "restarten" reloaden meinst, kann das sein? Dieses Plugin wird nicht funktionieren, wenn du den reload Befehl verwendest.

**Comment by DragonfireHD** [comment]
Das Plugin funktioniert auch wenn gerestartet habe es wird nur der Clan gelöscht von den. SPIELERN

**Comment by Wertzui123** [comment]
> s ist doch doof wie soll ich updates hochladen oder andere Plugins?? Kannst du das nicht in MySQL oder so ändern
BedrockClans funktioniert ohne MySQL.

**Comment by DragonfireHD** [comment]
Das Plugin stürzt weder ab oder ein Fehlermeldung es wird nur beim resarten oder Starten gelöscht

**Comment by Wertzui123** [comment]
Ich kann dir ohne deine Dateien leider nicht helfen.

**Comment by DragonfireHD** [comment]
Welche dateien denn

**Comment by DragonfireHD** [comment]
Trotzdem wird es gelöscht

**Comment by Wertzui123** [comment]
Ich brauche trotzdem deine "players.json".

**Comment by DragonfireHD** [comment]
![Screenshot_20201013_190352](https://user-images.githubusercontent.com/50929188/95892484-edb87680-0d86-11eb-85a2-bb8b538226a3.jpg)


![Screenshot_20201013_190328_com android chrome](https://user-images.githubusercontent.com/50929188/95892510-f4df8480-0d86-11eb-8045-f527b06657cf.jpg)

**Comment by DragonfireHD** [comment]
Ups

**Comment by DragonfireHD** [comment]
![Screenshot_20201013_190313](https://user-images.githubusercontent.com/50929188/95892570-06c12780-0d87-11eb-996c-3d315d29103b.jpg)

**Comment by Wertzui123** [comment]
Okay, sind die Clans noch da (und haben die Spielern sie nur verlassen), oder geht auch /clan info ClanName nicht mehr?

**Comment by DragonfireHD** [comment]
Da grade neu raufgeladen das plugin gebau die Dateien werden erstellt habe alles löschen müssen damit ich denn bug so wegbekomme

**Comment by Wertzui123** [comment]
Ich hoffe ja.

**Comment by DragonfireHD** [comment]
Obwohl die es bereits gemacht haben nach dem Server Start oder Restart wird es quasi zurückgesetzt

**Comment by DragonfireHD** [comment]
Im clan.json werden sie gespeichert aber man kann sie nicht aufrufen da stehen auch die owner die es erstellt haben aber ich will mich nicht wiederholen

**Comment by Wertzui123** [comment]
Funktioniert es nach der Neuinstallation?

**Comment by DragonfireHD** [comment]
Das Plugin ist Neuinstallatiert funktioniert trotzdem nicht

**Comment by DragonfireHD** [comment]
Ok danke

**Comment by Wertzui123** [comment]
Auf meinem Server funktioniert es ohne Probleme. Bitte probiere diese Version und sende mir, was in der Konsole steht, wenn BedrockClans startet: https://poggit.pmmp.io/ci/Wertzui123/BedrockClans/BedrockClans/dev:53

**Comment by Wertzui123** [comment]
Du musst BedrockClans selber builden oder als Ordner auf deinem Server starten, da Poggit diesen Branch nicht kennt.

**Comment by DragonfireHD** [comment]
Also ich habe das plugin ausgetauscht in BravoClans und dort exestiert der bug nicht aber ich will das plugin nicht nutzen da es kein PureChat exestiert dort

Mir ist was aufgefallen beim EventListener bei dir 

Es steht Quit Event drin und Login aber nicht das event zum Joinen

**Comment by HimmelKreis4865** [comment]
Was genau soll denn das PlayerJoinEvent bringen  wenn es doch schon im login gehandled wurde? 🤔

**Comment by DragonfireHD** [comment]
Hallo @HimmelKreis4865 schön das sie mit dabei sind in der runde erstmal 🙂

Also ich meine nicht das jetzt da am Code was fehlt oder so sondern das man paar sachen vergessen hat 

Zmb hab ich jetzt herausgefunden warum die Clans gelöscht werden obwohl sie exestieren es liegt am Farbcode
Wenn sie ein Clan erstellen mit farbe und abspeichern wird der name überschrieben also zmb so ihr clan heißt zmb jetzt

Ente sie schreiben denn namen in farbe also §6Ente
Aber das Plugin registert nicht das farbe ist und schreibt denn namen im json datei so rein - > 6EnteA = Plötzlich ist es ein komplett anderer name aber denn du nicht schreiben wolltest du wolltest Ente schreiben in Orange

Das ist auf dem Punkt gebracht ihr müsst das farbig schreiben irgendwie mit rein tun sonst kaufen sich die Spieler blin drauf los für 500 dollar einen Clan der sich dauernd umbennent

**Comment by DragonfireHD** [comment]
![Screenshot_20201015_014257](https://user-images.githubusercontent.com/50929188/96128809-1d39c100-0ef6-11eb-96ef-d028361d21d0.jpg)
-^
Ein bild mit dem Clan ohne Farbe ein clan mit farbe
-v
![Screenshot_20201015_014313](https://user-images.githubusercontent.com/50929188/96128814-1e6aee00-0ef6-11eb-980d-2b392bec197a.jpg)

**Comment by DragonfireHD** [comment]
Das untere ist mit farbe

**Comment by DragonfireHD** [comment]
Und sollte eigentlich nur DG heißen

**Comment by DragonfireHD** [comment]
In farbe

**Comment by DragonfireHD** [comment]
Und das komische A was man nicht eingeben hat

**Comment by DragonfireHD** [comment]
Und er löscht nur die Clans die davor bereits erstellt sind das dass Plugin trotzdem noch erkennt das diese Person aka Spieler immer noch ein Owner eines clans ist aber denn namen und Clan nicht mehr besitzt deswegen löscht er dauernd die neuen Clans von dem Spieler weil der Alte exestiert aber mit dem kompletten anderen namen wegen der farbe

**Comment by Wertzui123** [comment]
Ich denke nicht, dass das Plugin irgendwelche Clans löscht, sondern, dass die Clan-Namen ein Zeichen enthalten, das die Datenbank nicht unterstützt. Somit hängt dieses Problem mit #16 zusammen.
