### ISSUE TITLE
Support for the new ScoreHud api

### ISSUE THREAD

**Issue by MrNinja008** [Wertzui123/BedrockClans#29]
Pls make a addon for scorehud verison 6.0.0+ jackmd scorehud plugin pls it makes server less lag!

**Comment by MrNinja008** [comment]
@Wertzui123  so here it is 😉
https://github.com/MrNinja008/BedrockScoreTags

**Comment by Wertzui123** [comment]
Thanks!
Are you OK with me updating my ScoreHud Addon later too?

**Comment by MrNinja008** [comment]
> Thanks!
> Are you OK with me updating my ScoreHud Addon later too?
Ofc! btw now it is ScoreTags Not Add-ons If you tell addons means people will think 5.0.0+ addon. Can you able to check my dms? MrNinja008#8877

**Comment by Wertzui123** [comment]
> btw now it is ScoreTags Not Add-ons If you tell addons means people will think 5.0.0+ addon

You're right.

> Can you able to check my dms? MrNinja008#8877

Looks like my message wasn't sent due to a bad connection, I will write it again.

**Comment by Wertzui123** [comment]
I have added built-in ScoreHud support to BedrockClans in cb3531c.
