### ISSUE TITLE
make plugin support for purechat

### ISSUE THREAD

**Issue by roxtigger2003** [Wertzui123/BedrockClans#3]
i dont know how to config popup nametag or chat

 i dont know english

**Comment by Wertzui123** [comment]
Wich language do you speak?

**Comment by Wertzui123** [comment]
And what do you mean with config popup

**Comment by roxtigger2003** [comment]
> Wich language do you speak?

Vietnamese

**Comment by roxtigger2003** [comment]
> And what do you mean with config popup

like show name clan on nametag and chat
for example: in purechat:
  Builder:
    nametag: '{Clan_Name} [§l§dBuilder§r] {display_name}'
    chat: {Clan_Name} §e§l•Thợ §dHồ• §b{display_name} §e>> §b{msg}

**Comment by Wertzui123** [comment]
No, this is curently not possible because my fork doesn work.

**Comment by Wertzui123** [comment]
You can now use my PureChat Fork to enable BedrockClans support:

https://github.com/Wertzui123/PureChat
