### ISSUE TITLE
Top clans?

### ISSUE THREAD

**Issue by Mencoreh** [Wertzui123/BedrockClans#30]
It will be cool if you add a top clans system, like for each kill, the clan gains 1 point and lose one for each death

**Comment by Wertzui123** [comment]
> add a killing points system
> No

(#1)
This is a clan plugin and should be more like a party system than a faction system.

Also, a leaderboard has already been suggested: https://github.com/Wertzui123/BedrockClans/issues/1#issuecomment-569969488
