### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by EvilDevil1175** [Wertzui123/BedrockClans#31]
you can make clans join but only by invite / clan invite <player> as it is annoying that it is only for op and clan members cannot stick to each other

**Comment by Wertzui123** [comment]
OP players can join every clan using `/clan join` and clan members can invite other people into their clan using `/clan invite`.

> clan members cannot stick to each other

What do you mean?

**Comment by EvilDevil1175** [comment]
no pvp, with clan members

**Comment by Wertzui123** [comment]
No, this is not a factions plugin.
