### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MrNinja008** [Wertzui123/BedrockClans#34]
• a Scorehud ScoreTags  for scorehud version 6.0.0+++
• Top Clan Leaderboard
• Able to disable commands like bank bla bla via config
• A Clan UI Like if you dont have a clan it will show  just **create** button if you are owner it will show all clan buttons if you are member it will dont show delete or create button. 
• able to increase clan member slots
• Database support
• cooldown if member left a clan they need to wait 5min to join the clan back
• FIX EXPOLIT
 2 people in a clan x person left the clan and y person atck the x person to get clan points after that y person invite x person back to the clan -.-

**Comment by MrNinja008** [comment]
I am going to create clan tags:)

**Comment by MrNinja008** [comment]
Dont mind the last expolit issue i thought this is BravoClan

**Comment by Wertzui123** [comment]
> a Scorehud ScoreTags for scorehud version 6.0.0+++

Duplicated.

> Top Clan Leaderboard

Duplicated.

> Able to disable commands like bank bla bla via config

https://github.com/Wertzui123/BedrockClans/blob/master/resources/config.yml#L58

> A Clan UI Like if you dont have a clan it will show just create button if you are owner it will show all clan buttons if you are member it will dont show delete or create button.

Duplicated.

> able to increase clan member slots

There are no clan member slots.

> Database support

Of course it uses a database.

> cooldown if member left a clan they need to wait 5min to join the clan back

OK.

> • FIX EXPOLIT
2 people in a clan x person left the clan and y person atck the x person to get clan points after that y person invite x person back to the clan -.-

What are clan points?

Seriously, please put a little bit more effort into your issues next time.

**Comment by Wertzui123** [comment]
Please create a new issue for:
> cooldown if member left a clan they need to wait 5min to join the clan back
