### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by mesiiiiiii** [Wertzui123/BedrockClans#37]
13:12:16 Server|CRITICAL > ErrorException: "Undefined index: XhalconX1618" (EXCEPTION) in "plugins/BedrockClans-3.4.phar/src/Wertzui123/BedrockClans/Main" at line 200
13:12:16 Server|CRITICAL > #0 plugins/BedrockClans-3.4.phar/src/Wertzui123/BedrockClans/Main(200): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[29] Undefined index: XhalconX1618, string[89] phar:///home/container/plugins/BedrockClans-3.4.phar/src/Wertzui123/BedrockClans, integer 200, array[1])
13:12:16 Server|CRITICAL > #1 plugins/PureChat-master.phar/src/_64FF00/PureChat/clans/BedrockClans(37): Wertzui123\BedrockClans\Main->getPlayer(object pocketmine\Player)
13:12:16 Server|CRITICAL > #2 plugins/PureChat-master.phar/src/_64FF00/PureChat/PureChat(519): _64FF00\PureChat\clans\BedrockClans->getPlayerClan(object pocketmine\Player)
13:12:16 Server|CRITICAL > #3 plugins/PureChat-master.phar/src/_64FF00/PureChat/PureChat(562): _64FF00\PureChat\PureChat->applyPCTags(string[39] ..c{clan_name} ..r..d[...] XhalconX1618, object pocketmine\Player, string[0] , NULL )
13:12:16 Server|CRITICAL > #4 plugins/InfoTag.phar/src/AmmyRQ/InfoTag/API(76): _64FF00\PureChat\PureChat->getNametag(object pocketmine\Player)
13:12:16 Server|CRITICAL > #5 plugins/InfoTag.phar/src/AmmyRQ/InfoTag/Main(88): AmmyRQ\InfoTag\API::resetNametag(object pocketmine\Player)
13:12:16 Server|CRITICAL > #6 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): AmmyRQ\InfoTag\Main->onEntityLevelChangeEvent(object pocketmine\event\entity\EntityLevelChangeEvent)
13:12:16 Server|CRITICAL > #7 pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object AmmyRQ\InfoTag\Main, object pocketmine\event\entity\EntityLevelChangeEvent)
13:12:16 Server|CRITICAL > #8 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\entity\EntityLevelChangeEvent)
13:12:16 Server|CRITICAL > #9 pmsrc/src/pocketmine/entity/Entity(2507): pocketmine\event\Event->call()
13:12:16 Server|CRITICAL > #10 pmsrc/src/pocketmine/Player(1042): pocketmine\entity\Entity->switchLevel(object pocketmine\level\Level)
13:12:16 Server|CRITICAL > #11 pmsrc/src/pocketmine/entity/Entity(2330): pocketmine\Player->switchLevel(object pocketmine\level\Level)
13:12:16 Server|CRITICAL > #12 pmsrc/src/pocketmine/entity/Entity(2355): pocketmine\entity\Entity->setPosition(object pocketmine\level\Position)
13:12:16 Server|CRITICAL > #13 pmsrc/src/pocketmine/entity/Entity(2488): pocketmine\entity\Entity->setPositionAndRotation(object pocketmine\level\Position, double 356.95654296875, double 14.913223266602)
13:12:16 Server|CRITICAL > #14 pmsrc/src/pocketmine/Player(4271): pocketmine\entity\Entity->teleport(object pocketmine\level\Position, NULL , NULL )
13:12:16 Server|CRITICAL > #15 plugins/theSpawn.phar/src/supercrafter333/theSpawn/theSpawn(343): pocketmine\Player->teleport(object pocketmine\level\Position)
13:12:16 Server|CRITICAL > #16 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): supercrafter333\theSpawn\theSpawn->onPlayerLogin(object pocketmine\event\player\PlayerLoginEvent)
13:12:16 Server|CRITICAL > #17 pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object supercrafter333\theSpawn\theSpawn, object pocketmine\event\player\PlayerLoginEvent)
13:12:16 Server|CRITICAL > #18 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\player\PlayerLoginEvent)
13:12:16 Server|CRITICAL > #19 pmsrc/src/pocketmine/Player(2360): pocketmine\event\Event->call()
13:12:16 Server|CRITICAL > #20 pmsrc/src/pocketmine/Player(2340): pocketmine\Player->completeLoginSequence()
13:12:16 Server|CRITICAL > #21 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(142): pocketmine\Player->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket)
13:12:16 Server|CRITICAL > #22 pmsrc/src/pocketmine/network/mcpe/protocol/ResourcePackClientResponsePacket(62): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket)
13:12:16 Server|CRITICAL > #23 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(126): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
13:12:16 Server|CRITICAL > #24 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(133): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket)
13:12:16 Server|CRITICAL > #25 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(126): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
13:12:16 Server|CRITICAL > #26 pmsrc/src/pocketmine/Player(3565): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
13:12:16 Server|CRITICAL > #27 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
13:12:16 Server|CRITICAL > #28 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[21] 181.226.111.160 53918, object raklib\protocol\EncapsulatedPacket, integer 0)
13:12:16 Server|CRITICAL > #29 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
13:12:16 Server|CRITICAL > #30 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
13:12:16 Server|CRITICAL > #31 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
13:12:16 Server|CRITICAL > #32 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
13:12:16 Server|CRITICAL > #33 pmsrc/src/pocketmine/Server(2265): pocketmine\snooze\SleeperHandler->sleepUntil(double 1633439536.7088)
13:12:16 Server|CRITICAL > #34 pmsrc/src/pocketmine/Server(2105): pocketmine\Server->tickProcessor()
13:12:16 Server|CRITICAL > #35 pmsrc/src/pocketmine/Server(1689): pocketmine\Server->start()
13:12:16 Server|CRITICAL > #36 pmsrc/src/pocketmine/PocketMine(314): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
13:12:16 Server|CRITICAL > #37 pmsrc/src/pocketmine/PocketMine(344): pocketmine\server()
13:12:16 Server|CRITICAL > #38 pmsrc(11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
13:12:16 Server|INFO > XhalconX1618[/181.226.111.160:53918] logged out due to Internal server error

**Comment by Wertzui123** [comment]
Hi, why did you close the issue? Was the bug your fault?

**Comment by mesiiiiiii** [comment]
It was the plugin theSpawn

**Comment by Wertzui123** [comment]
Ok, I'll mark this as invalid then.

**Comment by Wertzui123** [comment]
Send the stack trace of the crash today, please.

**Comment by Wertzui123** [comment]
Closed due to deletion of the OPs account.
