### ISSUE TITLE
Update PHP 8.0

### ISSUE THREAD

**Issue by Sulfuritium** [Wertzui123/BedrockClans#38]
Hello, can you update your plugin under PHP 8.0?

The /clan invite crash ...

TypeError: "Wertzui123\BedrockClans\Clan::rankToNumber(): Argument #1 ($rank) must be of type string, null given, called in /home/container/plugins/BedrockClans-master/src/Wertzui123/BedrockClans/BCPlayer.php on line 110" (EXCEPTION) in "plugins/BedrockClans-master/src/Wertzui123/BedrockClans/Clan" at line 402

**Comment by Sulfuritium** [comment]
Hello, have you fixed it?

**Comment by Wertzui123** [comment]
Since this issue is still open, no.

**Comment by Wertzui123** [comment]
Is it possible that you're not really part of your clan?
Could you please try if your name appears in `/clan info`?

**Comment by Wertzui123** [comment]
Closing this due to unreproducibility and inactivity.
