### ISSUE TITLE
/clan leader (spielername) BUG :)

### ISSUE THREAD

**Issue by galaxytwenty** [Wertzui123/BedrockClans#39]
Bei dem befehl /clan leader (Spielername) kommt beim Empfänger eine leere Nachricht.

Reproduce:
Spieler1(leader) lädt Spieler2 in einem Clan ein
Spieler1(leader) macht /clan leader Spieler2

eine Nachricht bei Spieler2 Kommt ohne Inhalt :)

Liebe Grüße

**Comment by Wertzui123** [comment]
This was fixed in the latest commit.
Thanks for reporting.
