### ISSUE TITLE
API 4 Not loading Message

### ISSUE THREAD

**Issue by DragonfireHD** [Wertzui123/BedrockClans#40]
Could not load plugin '/home/minecraft/plugins/BedrockClans_dev-73.phar': Invalid plugin manifest: Invalid Plugin "permissions": Nested permission declarations are no longer supported. Declare each permission separately.

**Comment by Wertzui123** [comment]
Please use the latest version.

**Comment by Wertzui123** [comment]
Looks like the Poggit CI doesn't build the latest version.
Please build BedrockClans manually or wait for me to resolve the issue.

**Comment by Wertzui123** [comment]
The CI now works again.
You can download the latest build here: https://poggit.pmmp.io/ci/Wertzui123/BedrockClans/BedrockClans/dev:74

Sorry for the problem @DragonfireHD.
