### ISSUE TITLE
Disable idea clan invites 

### ISSUE THREAD

**Issue by GamerMJay** [Wertzui123/BedrockClans#41]
My idea: that you can disable clan invites, maybe owners don't want a clan invite, then they can just type /clan toggle maybe

**Comment by Wertzui123** [comment]
You can now do this by setting the minimum ranked required rank for clan invites to `leader`.
https://github.com/Wertzui123/BedrockClans/commit/56e1034f69f45cc30b6dafd36b6b5f77cb51de76
