### ISSUE TITLE
Idea ClanWar 💡 

### ISSUE THREAD

**Issue by DevGod6969** [Wertzui123/BedrockClans#43]
Add Clan Wars In which the leader/Owner of the clan can type /clanwar attack (opponent clan name) and opponent can type /clanwar accept (attacker clan name) and there will be a timer in chat which they will get 10 mins to prepare after 24 hours end all the clan members in attackers who are online will be selected as attackers and the opponent clan members are online will be selected as opponent the players who were in the clan but were offline will be in gamemode spectator and and see the clan war and the can war will be pvp fight in which you can give developer to add there custom cmds or stuffs.

Sorry if you don't understood it my english is bad

**Comment by Wertzui123** [comment]
Hello, thanks for your suggestion. Actually, I am trying to not make BedrockClans a faction plugin. Maybe I will optionally add such features sometime in the future, but not in the near one.

**Comment by DevGod6969** [comment]
👍
