### ISSUE TITLE
Crashed 

### ISSUE THREAD

**Issue by 2cool4u567** [Wertzui123/BedrockClans#6]
14.11 03:04:32 [Server] Server thread/CRITICAL ErrorException: "include(phar:///plugins/BedrockClans_dev-24.phar/src/Wertzui123/BedrockClans/BCPlayer.php): failed to open stream: phar error: Cannot open phar archive "/plugins/BedrockClans_dev-24.phar" for reading" (EXCEPTION) in "vendor/pocketmine/spl/BaseClassLoader" at line 126
14.11 03:04:32 [Server] Server thread/DEBUG #0 vendor/pocketmine/spl/BaseClassLoader(126): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string[291] include(phar:///plugins/BedrockCla, string[114] phar:///custom-php7.2.phar/vendor/, integer 126, array[2])
14.11 03:04:32 [Server] Server thread/DEBUG #1 vendor/pocketmine/spl/BaseClassLoader(126): include()
14.11 03:04:32 [Server] Server thread/DEBUG #2 (): BaseClassLoader->loadClass(string[32] Wertzui123\BedrockClans\BCPlayer)
14.11 03:04:32 [Server] Server thread/DEBUG #3 plugins/BedrockClans_dev-24.phar/src/Wertzui123/BedrockClans/Main(74): spl_autoload_call(string[32] Wertzui123\BedrockClans\BCPlayer)
14.11 03:04:32 [Server] Server thread/DEBUG #4 plugins/BedrockClans_dev-24.phar/src/Wertzui123/BedrockClans/listener/EventListener(30): Wertzui123\BedrockClans\Main->addPlayer(object pocketmine\Player)
14.11 03:04:32 [Server] Server thread/DEBUG #5 src/pocketmine/plugin/MethodEventExecutor(38): Wertzui123\BedrockClans\listener\EventListener->onLogin(object pocketmine\event\player\PlayerLoginEvent)
14.11 03:04:32 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(object Wertzui123\BedrockClans\listener\EventListener, object pocketmine\event\player\PlayerLoginEvent)
14.11 03:04:32 [Server] Server thread/DEBUG #7 src/pocketmine/event/Event(97): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\player\PlayerLoginEvent)
14.11 03:04:32 [Server] Server thread/DEBUG #8 src/pocketmine/Player(2196): pocketmine\event\Event->call()
14.11 03:04:32 [Server] Server thread/DEBUG #9 src/pocketmine/Player(2179): pocketmine\Player->completeLoginSequence()
14.11 03:04:32 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(126): pocketmine\Player->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket)
14.11 03:04:32 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/protocol/ResourcePackClientResponsePacket(62): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket)
14.11 03:04:32 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
14.11 03:04:32 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/protocol/BatchPacket(126): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket)
14.11 03:04:32 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
14.11 03:04:32 [Server] Server thread/DEBUG #15 src/pocketmine/Player(3204): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
14.11 03:04:32 [Server] Server thread/DEBUG #16 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
14.11 03:04:32 [Server] Server thread/DEBUG #17 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[19] 206.45.155.74 55602, object raklib\protocol\EncapsulatedPacket, integer 0)
14.11 03:04:32 [Server] Server thread/DEBUG #18 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
14.11 03:04:32 [Server] Server thread/DEBUG #19 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
14.11 03:04:32 [Server] Server thread/DEBUG #20 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
14.11 03:04:32 [Server] Server thread/DEBUG #21 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
14.11 03:04:32 [Server] Server thread/DEBUG #22 src/pocketmine/Server(2356): pocketmine\snooze\SleeperHandler->sleepUntil(double 1573700672.5213)
14.11 03:04:32 [Server] Server thread/DEBUG #23 src/pocketmine/Server(2213): pocketmine\Server->tickProcessor()
14.11 03:04:32 [Server] Server thread/DEBUG #24 src/pocketmine/Server(1791): pocketmine\Server->start()
14.11 03:04:32 [Server] Server thread/DEBUG #25 src/pocketmine/PocketMine(275): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[47] /, string[55] /plugins/)

**Comment by Wertzui123** [comment]
Your .phar is broken, try poggits one.
