### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by jaylac2000** [Wertzui123/BedrockClans#7]
Plugin Suggestions:
1. Add /topclan (where you can /clan donate <amount> to try and get top clan (EconomyAPI)
2. Clan chat have on/off feature like /clan chat on
3. have multiple ranks in a clan Leader, CO-Leader, Moderator,  Member

Scorehud Suggestions: 

1. Rather than show members name with members make it show like members: 2 rather than IGNs

If you do this suggestion maybe

Name: 
Rank: 
Members: 
Money: 
Rate: 

Example: 
Name: TestClan
Rank: Leader
Members: 1
Money: 4000
Rate: 3 

(rate meaning you are top 3rd) - just using my example

**Comment by Wertzui123** [comment]
Thanks for your suggestions, I'll take a look at them later.

**Comment by jaylac2000** [comment]
No problem

**Comment by Wertzui123** [comment]
https://github.com/Wertzui123/ScoreHud-Addons/commit/72e5be030db5f6a981d0f8acc2668b55baac7ee9

**Comment by Wertzui123** [comment]
> Clan chat have on/off feature like /clan chat on

Do you mean there should be a /clan togglechat command? Turning the clan-chat off is already possible in the config.yml.

**Comment by jaylac2000** [comment]
i mean when playing the game

you can do /clan chat <mgs> rn but maybe add the feature

/clan chat on - keeps your chat to clan chat until you turn it off that way you dont need to /clan chat <msg> everytime

**Comment by Wertzui123** [comment]
D you mean something like:

---
/clan chat on
Hey, how are you guys?
I don't even need to do /clan chat any more!
/clan chat off
---

?

**Comment by Wertzui123** [comment]
Hi, you didn't response to my last message. Please explain what you mean.

**Comment by Wertzui123** [comment]
These features were added in version 3.0 (except top-clans, but I don't think they will be implemented soon).

**Comment by jaylac2000** [comment]
ight cool. best and ONLY clan plugin i can find. perfect for my COMING SOON prisons server. tyty
