### ISSUE TITLE
PureChat Support?

### ISSUE THREAD

**Issue by MonoAdrian23** [Wertzui123/BedrockClans#8]
Youre PureChat Fork doesnt work with Bedrockclans
Pocketmine 3.12.0
Bedrockclans Latest
PureChat by Wertzui

**Comment by Wertzui123** [comment]
What's the problem?

**Comment by MonoAdrian23** [comment]
Egal in welchem Format es geschrieben wird, auch mithilfe von mehreren Usern wird es von PureChat als No Valid Factions erkannt.
Auch in der Config ist es auf Bedrockclans eingestellt.
Faction Support ist dennoch deaktiviert.
Chatformat ist aber korrekt

**Comment by MonoAdrian23** [comment]
Wäre echt mega von dir wenn du unter einer der Beiden Plugins eine exakte Erklärung schreiben würdest. 
Dein Clan Plugin ist nämlich das einzige gute unter vielen!

**Comment by Wertzui123** [comment]
Hallo,

danke für dein Lob. (;
Eine Erklärung werde ich hinzufügen.

Nun zu deinem Problem:
Könntest du bitte deine config.yml von PureChat über z.B. hastebin schicken?

**Comment by Wertzui123** [comment]
https://github.com/Wertzui123/BedrockClans/commit/a4b64c7f17e688f3df89badcf97135d0a2a9d5db

**Comment by MonoAdrian23** [comment]
Yes
