### ISSUE TITLE
Alles gemacht wie gesagt!

### ISSUE THREAD

**Issue by MonoAdrian23** [Wertzui123/BedrockClans#9]
Das PureChat wurde bei der Dev 31 exakt mit deiner Fork, wie beschrieben eingerichtet.
Das einzige was passiert ist aber das man seinen Rang nicht mehr angezeigt bekommt.
Wieso ist das so kompliziert?
Kann du nicht ein Video Tutorial machen?
Es ist doch viel einfacher einzelne Schritte in einem Video zu erklären, als ein Tutorial wo kein Mensch weiss was exakt wohin gehört.

**Comment by Wertzui123** [comment]
Bitte benutze deine alte Issue,
